repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
        name: Gitleaks Secret Scan
        description: Detect hardcoded secrets using Gitleaks
        args: ["--verbose"]