name: 'CD: Terraform Deploy'

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Module to deploy"
        required: true
      image_uri:
        description: "Full ECR Image URI"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_REGION: "eu-central-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          # Tells Trivy to scan Infrastructure as Code (Terraform) instead of a container image
          scan-type: 'config' 
          scan-ref: 'modules/${{ github.event.inputs.module }}'
          format: 'table'
          # Fails the deployment if misconfigurations are found
          exit-code: '1' 
          severity: 'CRITICAL,HIGH'

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActionsDeploymentRole
          aws-region: ${{ env.AWS_REGION }}


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Terraform Init & Apply
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          cd modules/${{ github.event.inputs.module }}
          terraform init \
            -backend-config="bucket=do-not-delete-awsgoat-state-files-$ACCOUNT_ID" \
            -backend-config="key=${{ github.event.inputs.module }}/terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"
          terraform apply -auto-approve \
            -var="ecs_image_uri=${{ github.event.inputs.image_uri }}"

      - name: Capture Application URL
        id: get-url
        run: |
          cd modules/${{ github.event.inputs.module }}
          # Extract the raw URL string from Terraform and save it to GitHub's environment
          RAW_URL=$(terraform output -raw ad_Target_URL)
          echo "APP_URL=https://$RAW_URL" >> $GITHUB_ENV
          echo "Targeting ZAP Scan at: https://$RAW_URL"

      - name: Run OWASP ZAP Full Active Scan
        uses: zaproxy/action-full-scan@v0.12.0 # Note the change from action-baseline
        with:
          target: '${{ env.APP_URL }}'
          fail_action: false 
          # Crucial: Limits the initial link-crawling spider to 2 minutes
          cmd_options: '-m 2' 
          
      - name: Gate Deployment on High Severities
        run: |
          HIGH_ALERTS=$(grep -c '"riskcode": "3"' report_json.json || true)
          if [ "$HIGH_ALERTS" -gt 0 ]; then
            echo "ERROR: ZAP found $HIGH_ALERTS High severity vulnerability(ies)!"
            exit 1
          else
            echo "SUCCESS: No High severity vulnerabilities found."
          fi
